apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: nginx-stateful
  namespace: reza-stateful

spec:
  updateStrategy:
    type: OnDelete
  serviceName: "nginx"
  selector:
    matchLabels:
      app: nginx
  replicas: 3
  template:
    metadata:
      labels:
        app: nginx
    spec:
     containers:
     - name: nginx
       image: nginx
       ports:
        - containerPort: 80
          name: web
